#!/bin/bash
echo "🚀 Streamlit Cloud 部署指南"
echo "1. 创建GitHub仓库: https://github.com/new"
echo "2. 仓库名: store-revenue-predictor (建议私有)"
echo "3. 推送代码:"
echo "   git init"
echo "   git add ."
echo "   git commit -m '初始提交'"
echo "   git remote add origin https://github.com/YOUR_USERNAME/store-revenue-predictor.git"
echo "   git push -u origin main"
echo "4. 访问: https://share.streamlit.io"
echo "5. 连接GitHub，选择仓库和app.py"
echo "6. 点击 Deploy!"
echo "7. 获得URL: https://store-revenue-predictor.streamlit.app"